### PR TITLE
Add more verbose error logging for failures

### PR DESCRIPTION
**Pull request by ryanwholey**
Ensures that any real error message returned from the API appears on the error.message field. I opted for pushing this into the client so if we want to get rid of axios, we dont have to change the code. As long as the error.message field is correct, we should be good to go.

Before:
image

After:
image

### CODE REVIEW

**Review by bendrucker — APPROVED** [review]
This is best implemented by overriding `toString` instead of mutating the message. 

Well behaved clients should be calling `toString` and not accessing `message` directly. Confirmed that actions [does](https://github.com/actions/toolkit/blob/4bf916289e5e32bb7d1bd7f21842c3afeab3b25a/packages/core/src/core.ts#L138).

You'd create a custom error class, include `response` or `data` as a member, and then optionally return that error type when receiving a server error. Encoding that data as JSON would come on `toString`. 

The difference in an Action won't have any practical impact. Ina server environment it's better to pay the serialization cost at stringification time, which doesn't have to block a response and may never happen depending on log level or other config.

**Comment by bendrucker** [comment]
Also throw some more white space in here. Leave a blank line between errors in the chain and print JSON with newlines and indentation via `JSON.stringify(data, null, 2)`.

**Comment by ryanwholey** [comment]
I'm happy to have a go at a custom error class, it felt a bit heavy when I originally had it.

Were looking at something like...

```
class {
  constructor(request, response, message, stack){}
  toString(){}
}
... 
catch (err) { // on request error
  throw new RequestError(err.request, err.response, err.message, err.stack)
}
```

FWIW I'm more familiar with throwing custom errors from the server vs recreating custom errors on the client if that makes senes.

**Review by bendrucker — APPROVED** [review]

**Comment by bendrucker** [comment]
Yep pretty much! Errors are data within your program, but should implement a string method for printing for humans. Functions can choose to handle the error based on its data, or pass it up the chain. The top of the chain handles output.

**Pull request merged**
